# Generated by Django 5.2.11 on 2026-03-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('embedding', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='recognition.person')),
            ],
            options={
                'ordering': ['-time_in'],
                'unique_together': {('person', 'date')},
            },
        ),
    ]
